export const CATEGORIES = [
  "Acai Bowls",
  "Accessories",
  "Acupuncture",
  "Afghan",
  "African",
  "American (New)",
  "American (Traditional)",
  "Arcades",
  "Argentine",
  "Art Galleries",
  "Asian Fusion",
  "Australian",
  "Austrian",
  "Bagels",
  "Bakeries",
  "Bangladeshi",
  "Banks & Credit Unions",
  "Barbeque",
  "Bars",
  "Basque",
  "Beer Bar",
  "Beer Gardens",
  "Beer, Wine & Spirits",
  "Belgian",
  "Beverage Store",
  "Bikes",
  "Boating",
  "Bookstores",
  "Brasseries",
  "Brazilian",
  "Breakfast & Brunch",
  "Breweries",
  "Brewpubs",
  "British",
  "Bubble Tea",
  "Buffets",
  "Burgers",
  "Butcher",
  "CSA",
  "Cafes",
  "Cafeteria",
  "Cajun/Creole",
  "Candle Stores",
  "Candy Stores",
  "Cantonese",
  "Cards & Stationery",
  "Caribbean",
  "Caterers",
  "Champagne Bars",
  "Cheese Shops",
  "Cheesesteaks",
  "Chicken Shop",
  "Chicken Wings",
  "Chimney Cakes",
  "Chinese",
  "Chocolatiers & Shops",
  "Cinema",
  "Cocktail Bars",
  "Coffee & Tea",
  "Coffee Roasteries",
  "Colleges & Universities",
  "Colombian",
  "Comedy Clubs",
  "Comfort Food",
  "Community Service/Non-Profit",
  "Convenience Stores",
  "Cooking Classes",
  "Cosmetics & Beauty Supply",
  "Costumes",
  "Creperies",
  "Cuban",
  "Cupcakes",
  "Custom Cakes",
  "Czech",
  "Dance Clubs",
  "Day Spas",
  "Delis",
  "Department Stores",
  "Desserts",
  "Dim Sum",
  "Diners",
  "Dinner Theater",
  "Discount Store",
  "Distilleries",
  "Dive Bars",
  "Do-It-Yourself Food",
  "Dominican",
  "Donuts",
  "Drugstores",
  "Egyptian",
  "Empanadas",
  "Ethiopian",
  "Falafel",
  "Farmers Market",
  "Farms",
  "Fast Food",
  "Festivals",
  "Filipino",
  "Fish & Chips",
  "Florists",
  "Flowers & Gifts",
  "Fondue",
  "Food",
  "Food Court",
  "Food Delivery Services",
  "Food Stands",
  "Food Trucks",
  "French",
  "Fruits & Veggies",
  "Furniture Stores",
  "Gas Stations",
  "Gastropubs",
  "Gelato",
  "Georgian",
  "German",
  "Gift Shops",
  "Gluten-Free",
  "Greek",
  "Grocery",
  "Gyms",
  "Haitian",
  "Halal",
  "Hardware Stores",
  "Hawaiian",
  "Head Shops",
  "Health Markets",
  "Herbs & Spices",
  "Himalayan/Nepalese",
  "Honey",
  "Hong Kong Style Cafe",
  "Hookah Bars",
  "Hot Dogs",
  "Hot Pot",
  "Hotels",
  "Hotels & Travel",
  "Hungarian",
  "Hydroponics",
  "Ice Cream & Frozen Yogurt",
  "Imported Food",
  "Indian",
  "Indonesian",
  "International Grocery",
  "Internet Cafes",
  "Irish",
  "Irish Pub",
  "Italian",
  "Izakaya",
  "Japanese",
  "Japanese Curry",
  "Jazz & Blues",
  "Juice Bars & Smoothies",
  "Karaoke",
  "Kebab",
  "Kids Activities",
  "Korean",
  "Kosher",
  "Latin American",
  "Lebanese",
  "Live/Raw Food",
  "Local Flavor",
  "Lounges",
  "Macarons",
  "Malaysian",
  "Meat Shops",
  "Mediterranean",
  "Men's Clothing",
  "Mexican",
  "Middle Eastern",
  "Modern European",
  "Moroccan",
  "Motorcycle Gear",
  "Music Venues",
  "New Mexican Cuisine",
  "Newspapers & Magazines",
  "Nightlife",
  "Noodles",
  "Nurseries & Gardening",
  "Nutritionists",
  "Olive Oil",
  "Opera & Ballet",
  "Organic Stores",
  "Pakistani",
  "Pan Asian",
  "Pancakes",
  "Party & Event Planning",
  "Party Equipment Rentals",
  "Party Supplies",
  "Passport & Visa Services",
  "Pasta Shops",
  "Patisserie/Cake Shop",
  "Performing Arts",
  "Persian/Iranian",
  "Personal Chefs",
  "Peruvian",
  "Pharmacy",
  "Piano Bars",
  "Pizza",
  "Poke",
  "Polish",
  "Pool Halls",
  "Pop-Up Restaurants",
  "Pop-up Shops",
  "Portuguese",
  "Pretzels",
  "Printing Services",
  "Professional Services",
  "Public Markets",
  "Pubs",
  "Puerto Rican",
  "Ramen",
  "Reiki",
  "Restaurants",
  "Russian",
  "Salad",
  "Sandwiches",
  "Scandinavian",
  "Seafood",
  "Seafood Markets",
  "Shanghainese",
  "Shaved Ice",
  "Shipping Centers",
  "Shoe Stores",
  "Shopping",
  "Shopping Centers",
  "Singaporean",
  "Smokehouse",
  "Social Clubs",
  "Soul Food",
  "Soup",
  "Southern",
  "Souvenir Shops",
  "Spanish",
  "Speakeasies",
  "Specialty Food",
  "Sports Bars",
  "Sports Clubs",
  "Sports Wear",
  "Steakhouses",
  "Street Vendors",
  "Supper Clubs",
  "Surf Shop",
  "Sushi Bars",
  "Swimwear",
  "Szechuan",
  "Tabletop Games",
  "Tableware",
  "Tacos",
  "Taiwanese",
  "Tapas Bars",
  "Tapas/Small Plates",
  "Tea Rooms",
  "Teppanyaki",
  "Tex-Mex",
  "Thai",
  "Themed Cafes",
  "Tobacco Shops",
  "Tours",
  "Traditional Chinese Medicine",
  "Turkish",
  "Tuscan",
  "Ukrainian",
  "Used, Vintage & Consignment",
  "Uzbek",
  "Vacation Rentals",
  "Vape Shops",
  "Vegan",
  "Vegetarian",
  "Venezuelan",
  "Venues & Event Spaces",
  "Videos & Video Game Rental",
  "Vietnamese",
  "Vitamins & Supplements",
  "Waffles",
  "Whiskey Bars",
  "Wholesale Stores",
  "Wine Bars",
  "Wine Tasting Classes",
  "Wine Tasting Room",
  "Wineries",
  "Wraps",
  "Yoga",
];
