name: Compile server on merge
on:
  push:
    branches:
      - main
    paths: ["server/**"]
jobs:
  build_server:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: (cd server && npm ci)
      - run: (cd server && npm run build)
